# Generated by Django 3.1.5 on 2021-03-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Gerenciador',
            fields=[
                ('id', models.AutoField(db_column='id_gerenciador', primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receita_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesa_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gerenciador',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(db_column='id_receita', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebido', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('receita_fixa', models.BooleanField(default=False)),
                ('fixa_ativa', models.BooleanField(default=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='gerenciador.categoria')),
                ('id_gerenciador', models.ForeignKey(db_column='id_gerenciador', on_delete=django.db.models.deletion.CASCADE, to='gerenciador.gerenciador')),
            ],
            options={
                'verbose_name_plural': 'receitas',
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(db_column='id_despesa', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('despesa_fixa', models.BooleanField(default=False)),
                ('fixa_ativa', models.BooleanField(default=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='gerenciador.categoria')),
                ('id_gerenciador', models.ForeignKey(db_column='id_gerenciador', on_delete=django.db.models.deletion.CASCADE, to='gerenciador.gerenciador')),
            ],
            options={
                'verbose_name_plural': 'despesas',
                'db_table': 'despesa',
            },
        ),
    ]
